In [11]:
import sys
import numpy as np
sys.path.append('../')
import zlibrary.linear_system as ls
Cons = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [-1, 0, 1, 0, 0, 0, 1, 0, 0, 0],
                #  [-1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
                 [0, -1, 0, 1, 0, 0, 0, 1, 0, 0],
                #  [0, -1, 0, 0, 0, 1, 0, 0, 0, 1],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                #  [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
                #  [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
u = ls.find_basic_solution(Cons)
v = np.where(u == 1, 1, 0)
w = np.where(u == -1, 1, 0)
print(u)

[[1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
