In [1]:
import networkx as nx
import matplotlib.pyplot as plt

from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import Aer
from qiskit.circuit import Parameter
from qiskit.visualization import plot_histogram

import numpy as np
from scipy.optimize import minimize

In [2]:
GateX = np.array([[0, 1],[1, 0]])
GateY = np.array([[0, -1j],[1j, 0]])
GateZ = np.array([[1, 0],[0, -1]])

In [3]:
# dtype=np.complex128
def add_in_target(num_qubits, target_qubit, gate=np.array([[1, 0],[0, -1]])):
    H = np.eye(2 ** (target_qubit))
    H = np.kron(H, gate)
    H = np.kron(H, np.eye(2 ** (num_qubits - 1 - target_qubit)))
    return H
def gnrt_Hd():
  Hd = np.zeros((2**3, 2**3)).astype(np.complex128)
  Hd += (add_in_target(3, 0, GateX) @ add_in_target(3, 1, GateX) + add_in_target(3, 0, GateY) @ add_in_target(3, 1, GateY))
  Hd += (add_in_target(3, 1, GateX) @ add_in_target(3, 2, GateX) - add_in_target(3, 1, GateY) @ add_in_target(3, 2, GateY))
  Hd += (add_in_target(3, 2, GateX) @ add_in_target(3, 0, GateX) - add_in_target(3, 2, GateY) @ add_in_target(3, 0, GateY))
  # Hd += add_in_target(1, 0, GateX)
  # Hd += add_in_target(3, 1, GateX)
  # Hd += add_in_target(3, 2, GateX)
  return Hd

In [4]:
B = np.zeros(2**2)
B[0] = 1
B

array([1., 0., 0., 0.])

In [5]:
Hd = np.zeros((2**2, 2**2)).astype(np.complex128)
Hd + add_in_target(2, 1, GateX)

array([[0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j]])

In [6]:
add_in_target(2, 0, GateX)


array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [7]:
A = gnrt_Hd()
print(A)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

[[0.+0.j 0.+0.j 0.+0.j 2.+0.j 0.+0.j 2.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 2.+0.j 0.+0.j 0.+0.j 2.+0.j]
 [2.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 2.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 2.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 2.+0.j]
 [2.+0.j 0.+0.j 0.+0.j 2.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 2.+0.j 0.+0.j 2.+0.j 0.+0.j 0.+0.j 0.+0.j]]
Eigenvalues:
[-2.+0.j  4.+0.j -2.+0.j  4.+0.j -2.+0.j -2.+0.j  0.+0.j  0.+0.j]

Eigenvectors:
[[ 0.81649658+0.j  0.57735027+0.j  0.42493167-0.j  0.21551589-0.j
   0.26657948+0.j -0.1587708 +0.j  0.        +0.j  0.        +0.j]
 [-0.        -0.j -0.        -0.j -0.        -0.j -0.        -0.j
   0.        +0.j  0.        +0.j  1.        +0.j  0.        +0.j]
 [-0.        -0.j -0.        -0.j -0.34860427-0.j  0.53561762+0.j
   0.76513302+0.j -0.10618901+0.j  0.        +0.j  0.        +0.j]
 [-0.40824829-0.j  0.57735027-0.j 

In [25]:
A = gnrt_Hd()

# 求解本征值和本征态
eigenvalues, eigenvectors = np.linalg.eig(A)

# 输出结果
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors[:, 1])

Eigenvalues:
[-2.+0.j  4.+0.j -2.+0.j  4.+0.j -2.+0.j -2.+0.j  0.+0.j  0.+0.j]

Eigenvectors:
[ 0.57735027+0.j -0.        -0.j -0.        -0.j  0.57735027-0.j
 -0.        -0.j  0.57735027-0.j -0.        -0.j -0.        -0.j]


In [10]:
from qiskit import QuantumCircuit
import numpy as np

# 创建一个2量子比特的电路
qc = QuantumCircuit(2)

# 定义一个初始量子态
initial_state = np.array([1/np.sqrt(2), 1j/np.sqrt(2)])

# 使用initialize()方法将电路初始化为给定的量子态
qc.initialize(initial_state, [0])

# 绘制量子电路
print(qc.draw())


     ┌──────────────────────────────┐
q_0: ┤ Initialize(0.70711,0.70711j) ├
     └──────────────────────────────┘
q_1: ────────────────────────────────
                                     


In [27]:
import numpy as np

# 定义一个矩阵
matrix  = np.random.rand(10000, 10000)

# 计算特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# 将特征值和特征向量按照特征值的大小进行排序
sorted_indices = np.argsort(eigenvalues)
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]

# 输出特征值和对应的特征向量
for i in range(len(sorted_eigenvalues)):
    print("特征值:", sorted_eigenvalues[i])
    print("对应的特征向量:", sorted_eigenvectors[:, i])


特征值: (-28.724446727444594-1.3378092764389193j)
对应的特征向量: [ 0.00714735+0.01290664j  0.0047206 -0.00689643j -0.00881116+0.00345942j
 ... -0.00497559-0.00358831j -0.0064494 -0.0080174j
  0.00436125-0.0021699j ]
特征值: (-28.724446727444594+1.3378092764389193j)
对应的特征向量: [ 0.00714735-0.01290664j  0.0047206 +0.00689643j -0.00881116-0.00345942j
 ... -0.00497559+0.00358831j -0.0064494 +0.0080174j
  0.00436125+0.0021699j ]
特征值: (-28.68827400894087-0.8672934274799884j)
对应的特征向量: [ 0.00194541+0.01011514j  0.0034119 -0.00493495j -0.00424218-0.00148868j
 ...  0.00237843-0.00281425j -0.00118222-0.00199388j
  0.00191399-0.0006109j ]
特征值: (-28.68827400894087+0.8672934274799884j)
对应的特征向量: [ 0.00194541-0.01011514j  0.0034119 +0.00493495j -0.00424218+0.00148868j
 ...  0.00237843+0.00281425j -0.00118222+0.00199388j
  0.00191399+0.0006109j ]
特征值: (-28.605377065875505-4.043159806202125j)
对应的特征向量: [ 0.00727827-0.01297059j -0.00615374+0.01269838j  0.01591767-0.00130383j
 ... -0.00375625+0.01313181j  0.00447447+0.0