In [1]:
import networkx as nx
import matplotlib.pyplot as plt

from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import Aer
from qiskit.circuit import Parameter
from qiskit.visualization import plot_histogram

import numpy as np
from scipy.optimize import minimize

In [2]:
GateX = np.array([[0, 1],[1, 0]])
GateY = np.array([[0, -1j],[1j, 0]])
GateZ = np.array([[1, 0],[0, -1]])

def add_in_target(num_qubits, target_qubit, gate=np.array([[1, 0],[0, -1]])):
    H = np.eye(2 ** (target_qubit))
    H = np.kron(H, gate)
    H = np.kron(H, np.eye(2 ** (num_qubits - 1 - target_qubit)))
    return H
def gnrt_Hd():
  qnum = 2
  Hd = np.zeros((2**qnum, 2**qnum)).astype(np.complex128)
  Hd += add_in_target(2, 0, GateX)@add_in_target(2, 1, GateX) + add_in_target(2, 0, GateY)@add_in_target(2, 1, GateY)
  Hd += add_in_target(2, 1, GateX)@add_in_target(2, 0, GateX) + add_in_target(2, 1, GateY)@add_in_target(2, 0, GateY)
  return Hd

In [3]:
for i in range(4):
  B = np.zeros(4)
  B[i] = 1
  C = np.eye(2**2) + add_in_target(2, 0, GateX)@add_in_target(2, 1, GateX) + add_in_target(2, 0, GateY)@add_in_target(2, 1, GateY) + add_in_target(2, 0, GateZ)@add_in_target(2, 1, GateZ)
  print(B)
  print(C.dot(B))
  print("====")

[1. 0. 0. 0.]
[2.+0.j 0.+0.j 0.+0.j 0.+0.j]
====
[0. 1. 0. 0.]
[0.+0.j 0.+0.j 2.+0.j 0.+0.j]
====
[0. 0. 1. 0.]
[0.+0.j 2.+0.j 0.+0.j 0.+0.j]
====
[0. 0. 0. 1.]
[0.+0.j 0.+0.j 0.+0.j 2.+0.j]
====


In [4]:
gnrt_Hd()

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 4.+0.j, 0.+0.j],
       [0.+0.j, 4.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [5]:
B = np.array([0, 0, 0, 1])

In [6]:
gnrt_Hd().dot(B)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [7]:
np.kron(GateX, GateX)

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [8]:
import numpy as np

GateX = np.array([[0, 1],[1, 0]])
GateY = np.array([[0, -1j],[1j, 0]])
GateZ = np.array([[1, 0],[0, -1]])

def add_in_target(num_qubits, target_qubit, gate=np.array([[1, 0],[0, -1]])):
    H = np.eye(2 ** (target_qubit))
    H = np.kron(H, gate)
    H = np.kron(H, np.eye(2 ** (num_qubits - 1 - target_qubit)))
    return H

for i in range(16):
  B = np.zeros(16)
  B[i] = 1
  Z = np.zeros((2 ** 4, 2 ** 4)).astype(np.complex128)
  a = add_in_target(4, 0, GateX)@add_in_target(4, 1, GateX)@add_in_target(4, 2, GateX)@add_in_target(4, 3, GateX) + add_in_target(4, 0, GateY)@add_in_target(4, 1, GateY)@add_in_target(4, 2, GateY)@add_in_target(4, 3, GateY)
  b = add_in_target(4, 0, GateX)@add_in_target(4, 1, GateY)@add_in_target(4, 2, GateY)@add_in_target(4, 3, GateX) + add_in_target(4, 0, GateY)@add_in_target(4, 1, GateX)@add_in_target(4, 2, GateX)@add_in_target(4, 3, GateY)
  c = add_in_target(4, 0, GateX)@add_in_target(4, 1, GateY)@add_in_target(4, 2, GateX)@add_in_target(4, 3, GateY) + add_in_target(4, 0, GateY)@add_in_target(4, 1, GateX)@add_in_target(4, 2, GateY)@add_in_target(4, 3, GateX)
  d = add_in_target(4, 0, GateX)@add_in_target(4, 1, GateX)@add_in_target(4, 2, GateY)@add_in_target(4, 3, GateY) + add_in_target(4, 0, GateY)@add_in_target(4, 1, GateY)@add_in_target(4, 2, GateX)@add_in_target(4, 3, GateX)
  Z = a - b + c + d
  print(B.astype(int))
  print(Z.dot(B).astype(int).real)
  print("====")

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
====
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
====
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
====
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
====
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
====
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
====
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 8 0 0 0 0 0 0]
====
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
====
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
====
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 8 0 0 0 0 0 0 0 0 0]
====
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
====
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
====
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
====
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 

/tmp/ipykernel_56495/832025225.py:23: ComplexWarning: Casting complex values to real discards the imaginary part
  print(Z.dot(B).astype(int).real)
