In [1]:
from scipy.linalg import expm
import numpy as np

import sys
sys.path.append('../')
import z_library.linear_system as ls

ls.set_print_form(precision=3)

In [16]:
import sympy as sp

# 定义符号变量
a, b, c, d = sp.symbols('a b c d')

# 定义矩阵 A
A = sp.Matrix([[1j, b], [c, d]])

# 计算矩阵的指数幂 e^A
exp_A = sp.exp(A)

exp_A


Matrix([
[2.0*(-0.125*d**2 + 0.25*I*d + 0.5*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**1.0 + 0.125)*exp(0.5*d + 1.0*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**0.5 + 0.5*I)/((d + 2.0*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**0.5 - I)*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**0.5) + 2.0*(0.125*d**2 - 0.25*I*d - 0.5*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**1.0 - 0.125)*exp(0.5*d - 1.0*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**0.5 + 0.5*I)/((d - 2.0*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**0.5 - I)*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**0.5), 2.0*b*(-0.25*d**2 + 0.5*I*d + 1.0*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**1.0 + 0.25)*exp(0.5*d + 1.0*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**0.5 + 0.5*I)/((d + 2.0*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**0.5 - I)*(-1.0*d*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**0.5 + 1.0*I*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**0.5 + 2.0*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**1.0)) + 2.0*b*(-0.25*d**4 + 1.0*d**3*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**0.5 + 1.0*I*d**3 - 3.0*I*d**2*(b*c + 0.25*d**2 - 0.5*I*d - 0.25)**0.5 + 1.5*d**2 - 3.0*

In [38]:
import sympy as sp
## define the Hamiltonian
sigma_plus =sp.Matrix([[0,1],[0,0]])
sigma_minus =sp.Matrix([[0,0],[1,0]])
identity = sp.Matrix([[1,0],[0,1]])

mlist = {
    1: sigma_plus,
    0 : identity,
    -1: sigma_minus
}

def tensor_product(matrices):
    return sp.tensorproduct(*[mlist[i] for i in matrices])
    
def get_simulate_unitary(v):    
    contrary_v = [-i for i in v]
    t = sp.Symbol('t')
    U = sp.exp((-1*sp.I * t * (tensor_product(v)+tensor_product(contrary_v))).doit())
    return U

def get_simulate_unitary_two(v,u):    
    contrary_v = [-i for i in v]
    contrary_u = [-i for i in u]
    t = sp.Symbol('t')
    H = (tensor_product(v)+tensor_product(contrary_v)+ tensor_product(u)+tensor_product(contrary_u))
    print(H)
    U = expm(-1j * t * H)
    return U
## define the time-independent part of the Liouvillian
U = get_simulate_unitary_two([1,0],[1,-1])
U

## define the initial state

[[[[0, 0], [0, 0]], [[1, 0], [1, 1]]], [[[1, 1], [0, 1]], [[0, 0], [0, 0]]]]


TypeError: Cannot convert expression to float

In [31]:
t = sp.symbols('t')
U10=sp.exp(sp.Matrix([[0,0,-sp.I*t,0],[0,0,0,-sp.I*t],[-sp.I*t,0,0,0],[0,-sp.I*t,0,0]]))
U1m=sp.exp(sp.Matrix([[0,0,0,0],[0,0,-sp.I*t,0],[0,-sp.I*t,0,0],[0,0,0,0]]))

In [34]:
(U10@U1m).doit()

Matrix([
[ exp(I*t)/2 + exp(-I*t)/2,                         (-exp(I*t)/2 + exp(-I*t)/2)**2, (-exp(I*t)/2 + exp(-I*t)/2)*(exp(I*t)/2 + exp(-I*t)/2),                         0],
[                        0,                          (exp(I*t)/2 + exp(-I*t)/2)**2, (-exp(I*t)/2 + exp(-I*t)/2)*(exp(I*t)/2 + exp(-I*t)/2), -exp(I*t)/2 + exp(-I*t)/2],
[-exp(I*t)/2 + exp(-I*t)/2, (-exp(I*t)/2 + exp(-I*t)/2)*(exp(I*t)/2 + exp(-I*t)/2),                          (exp(I*t)/2 + exp(-I*t)/2)**2,                         0],
[                        0, (-exp(I*t)/2 + exp(-I*t)/2)*(exp(I*t)/2 + exp(-I*t)/2),                         (-exp(I*t)/2 + exp(-I*t)/2)**2,  exp(I*t)/2 + exp(-I*t)/2]])

In [45]:
t = sp.symbols('t')
U=sp.exp(sp.Matrix([[0,0,-sp.I*t,0],[0,0,-sp.I*t,-sp.I*t],[-sp.I*t,-sp.I*t,0,0],[0,-sp.I*t,0,0]]))
U

Matrix([
[sqrt(2)*sqrt(3 - sqrt(5))*(-sqrt(10) + sqrt(2))*exp(I*t*sqrt(3/2 - sqrt(5)/2))/((-1 + sqrt(5))*(-10*sqrt(3 - sqrt(5)) + 2*sqrt(5)*sqrt(3 - sqrt(5)))) - sqrt(2)*(-5*sqrt(2) + 2*sqrt(10))*sqrt(sqrt(5) + 3)*exp(I*t*sqrt(sqrt(5)/2 + 3/2))/((1 + sqrt(5))*(-20*sqrt(sqrt(5) + 3) + 10*sqrt(5)*sqrt(sqrt(5) + 3))) + sqrt(2)*sqrt(sqrt(5) + 3)*(-21*sqrt(10)*sqrt(sqrt(5) + 3) + 47*sqrt(2)*sqrt(sqrt(5) + 3))*exp(-I*t*sqrt(sqrt(5)/2 + 3/2))/((-160 + 72*sqrt(5))*(1 + sqrt(5))) - sqrt(2)*sqrt(3 - sqrt(5))*(-7*sqrt(2)*sqrt(3 - sqrt(5)) + 3*sqrt(10)*sqrt(3 - sqrt(5)))*exp(-I*t*sqrt(3/2 - sqrt(5)/2))/((-160 + 72*sqrt(5))*(-1 + sqrt(5))), sqrt(2)*sqrt(3 - sqrt(5))*(-4*sqrt(10) + 9*sqrt(2))*exp(I*t*sqrt(3/2 - sqrt(5)/2))/((-1 + sqrt(5))*(-25*sqrt(3 - sqrt(5)) + 11*sqrt(5)*sqrt(3 - sqrt(5)))) - sqrt(2)*(-3*sqrt(10) + 5*sqrt(2))*sqrt(sqrt(5) + 3)*exp(I*t*sqrt(sqrt(5)/2 + 3/2))/((1 + sqrt(5))*(-40*sqrt(sqrt(5) + 3) + 20*sqrt(5)*sqrt(sqrt(5) + 3))) + sqrt(2)*sqrt(sqrt(5) + 3)*(-29*sqrt(2)*sqrt(sqrt(5)

In [46]:
# 定义σ+和σ-矩阵
sigma_plus = np.array([[0, 1], [0, 0]])
sigma_minus = np.array([[0, 0], [1, 0]])
identity = np.array([[1, 0], [0, 1]])
matrix_map ={
    1: sigma_plus,
    -1: sigma_minus,
    0: identity
}
def tensor_product(us):
    result = matrix_map[us[0]]
    for u in us[1:]:
        result = np.kron(result, matrix_map[u])
    return result
    



In [47]:
tensor_product([-1,0])

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [48]:
import sympy as sp
def get_simulate_unitary(t,v):    
    contrary_v = [-i for i in v]
    U = expm(-1j * t * (tensor_product(v)+tensor_product(contrary_v)))
    return U

def get_simulate_unitary_two(t,v,u):    
    contrary_v = [-i for i in v]
    contrary_u = [-i for i in u]
    H = (tensor_product(v)+tensor_product(contrary_v)+ tensor_product(u)+tensor_product(contrary_u))
    print(H)
    U = expm(-1j * t * H)
    return U

In [49]:
U1= get_simulate_unitary(0.8,[-1,1])
U2 = get_simulate_unitary(0.8,[1,0])
Ud = U1@U2
U = get_simulate_unitary_two(0.8,[-1,1],[1,0])
U


[[0 0 1 0]
 [0 0 1 1]
 [1 1 0 0]
 [0 1 0 0]]


array([[ 0.712+0.j   , -0.272+0.j   ,  0.   -0.642j,  0.   +0.077j],
       [-0.272+0.j   ,  0.441+0.j   ,  0.   -0.565j,  0.   -0.642j],
       [ 0.   -0.642j,  0.   -0.565j,  0.441+0.j   , -0.272+0.j   ],
       [ 0.   +0.077j,  0.   -0.642j, -0.272+0.j   ,  0.712+0.j   ]])

In [50]:
Ud

array([[ 0.697+0.j   ,  0.   +0.j   ,  0.   -0.717j,  0.   +0.j   ],
       [-0.515+0.j   ,  0.485+0.j   ,  0.   -0.5j  ,  0.   -0.5j  ],
       [ 0.   -0.5j  ,  0.   -0.5j  ,  0.485+0.j   , -0.515+0.j   ],
       [ 0.   +0.j   ,  0.   -0.717j,  0.   +0.j   ,  0.697+0.j   ]])

In [11]:
Ud

array([[ 0.697+0.j   ,  0.   +0.j   ,  0.   -0.717j,  0.   +0.j   ],
       [-0.515+0.j   ,  0.485+0.j   ,  0.   -0.5j  ,  0.   -0.5j  ],
       [ 0.   -0.5j  ,  0.   -0.5j  ,  0.485+0.j   , -0.515+0.j   ],
       [ 0.   +0.j   ,  0.   -0.717j,  0.   +0.j   ,  0.697+0.j   ]])

In [43]:
U2@U1

array([[ 0.292+0.j   ,  0.   -0.455j, -0.708+0.j   ,  0.   -0.455j],
       [ 0.   -0.841j,  0.54 +0.j   ,  0.   +0.j   ,  0.   +0.j   ],
       [ 0.   +0.j   ,  0.   +0.j   ,  0.54 +0.j   ,  0.   -0.841j],
       [ 0.   -0.455j, -0.708+0.j   ,  0.   -0.455j,  0.292+0.j   ]])

In [191]:
initvec = np.random.rand(8)
initvec = initvec / np.linalg.norm(initvec)
print(initvec)
print(U @ initvec)
## get density matrix
rho = np.outer(initvec, initvec.conj().T)
print(rho)


[0.233 0.494 0.482 0.183 0.447 0.019 0.174 0.453]
[0.233+0.j    0.153+0.165j 0.482+0.j    0.183+0.j    0.447+0.j    0.019+0.j    0.054+0.47j  0.453+0.j   ]
[[0.054 0.115 0.112 0.043 0.104 0.005 0.04  0.106]
 [0.115 0.244 0.238 0.091 0.221 0.01  0.086 0.224]
 [0.112 0.238 0.232 0.088 0.215 0.009 0.084 0.218]
 [0.043 0.091 0.088 0.034 0.082 0.004 0.032 0.083]
 [0.104 0.221 0.215 0.082 0.2   0.009 0.078 0.203]
 [0.005 0.01  0.009 0.004 0.009 0.    0.003 0.009]
 [0.04  0.086 0.084 0.032 0.078 0.003 0.03  0.079]
 [0.106 0.224 0.218 0.083 0.203 0.009 0.079 0.206]]


In [211]:
from qiskit import QuantumCircuit
from qiskit import transpile

cir = QuantumCircuit(3)
cir.mcp(0.865555555, [0,1], 2)
new_cir = transpile(cir, basis_gates=['x','cp','y','z','cz','ccz','ccp','h'])
print(new_cir)

         ┌───┐       ┌───┐              ┌───┐   ┌───┐             
q_0: ────┤ H ├─────■─┤ H ├─■────────────┤ H ├─■─┤ H ├─■───────────
         └───┘     │ └───┘ │            └───┘ │ └───┘ │           
q_1: ─■────────────■───────┼──────────────────■───────┼───────────
      │P(0.43278)          │P(-0.43278)               │P(0.43278) 
q_2: ─■────────────────────■──────────────────────────■───────────
                                                                  


In [193]:
from qiskit import QuantumCircuit
from qiskit_aer import Aer
from qiskit.circuit.library import MCMT
from qiskit import transpile

# 输入qc, 返回电路酉矩阵
def get_circ_unitary(quantum_circuit):
  backend = Aer.get_backend('unitary_simulator' )
  new_circuit = transpile(quantum_circuit, backend)
  job = backend.run(new_circuit)
  result = job.result()
  unitary = result.get_unitary()
  return unitary

In [194]:
# 从q0加H后, cx控制其余门, 注意qiskit下标相反
from qiskit import QuantumCircuit
def iter_apply(qc,bitstring,i,num_qubits):
    flip = bitstring[0]==0
    if flip:
        bitstring = [not(j) for j in bitstring]
    if bitstring[1]:
        qc.x(num_qubits-i-1)
    qc.cx(num_qubits - i,num_qubits-(i+1))
    next_bitstring = bitstring[1:]
    if len(next_bitstring)>1:
        return iter_apply(qc,next_bitstring,i+1,num_qubits)
    else:
        return qc
        
    

def apply_convert(qc,bitstring):
    ## 1111
    num_qubits = len(bitstring)
    qc.x(num_qubits - 1)
    qc.h(num_qubits - 1)
    ## 1111+0111
    ##find bit start with 1
    iter_apply(qc,bitstring,1,num_qubits)

num_q = 3
qc = QuantumCircuit(num_q)
bitstring = [1,0,1]
for i in range(num_q-1):
    qc.x(i)
apply_convert(qc,bitstring)
qc.draw()

┌───┐          ┌───┐
q_0: ┤ X ├──────────┤ X ├
     ├───┤     ┌───┐└─┬─┘
q_1: ┤ X ├─────┤ X ├──■──
     ├───┤┌───┐└─┬─┘     
q_2: ┤ X ├┤ H ├──■───────
     └───┘└───┘

In [195]:
# 验证确实为 |101> + |010> 的叠加态
print(f'验证制备 的叠加态: {np.asarray(get_circ_unitary(qc))[:,0]}')


验证制备 的叠加态: [ 0.   +0.j  0.   +0.j  0.707-0.j  0.   +0.j  0.   +0.j -0.707+0.j  0.   +0.j  0.   +0.j]


In [196]:
def reversed_iter_apply(qc,bitstring,i,num_qubits):
    flip = bitstring[0]==0
    if flip:
        bitstring = [not(j) for j in bitstring]
    if len(bitstring)>1:
        reversed_iter_apply(qc,bitstring[1:],i+1,num_qubits)
    else:
        return qc
    qc.cx(num_qubits - i,num_qubits-(i+1))
    if bitstring[1]:
        qc.x(num_qubits-i-1)
    return qc
    

def reverse_apply_convert(qc,bitstring):
    ## 1111
    num_qubits = len(bitstring)
    reversed_iter_apply(qc,bitstring,1,num_qubits)
    qc.h(num_qubits - 1)
    qc.x(num_qubits - 1)
    ## 1111+0111
    ##find bit start with 1

num_q = 3
qc = QuantumCircuit(num_q)
bitstring = [1,0,1]
for i in range(num_q):
    qc.x(i)
reverse_apply_convert(qc,bitstring)
qc.draw()

┌───┐┌───┐               
q_0: ┤ X ├┤ X ├───────────────
     ├───┤└─┬─┘┌───┐          
q_1: ┤ X ├──■──┤ X ├──────────
     ├───┤     └─┬─┘┌───┐┌───┐
q_2: ┤ X ├───────■──┤ H ├┤ X ├
     └───┘          └───┘└───┘

In [197]:
print(f'验证反向的态: {np.asarray(get_circ_unitary(qc))[:,0]}')

验证反向的态: [-0.707+0.j  0.   +0.j  0.   +0.j  0.   +0.j  0.707-0.j  0.   +0.j  0.   +0.j  0.   +0.j]


In [198]:
def iter_apply(qc,bitstring,i,num_qubits):
    flip = bitstring[0]==0
    if flip:
        bitstring = [not(j) for j in bitstring]
    if bitstring[1]:
        qc.x(num_qubits-i-1)
    qc.cx(num_qubits - i,num_qubits-(i+1))
    next_bitstring = bitstring[1:]
    if len(next_bitstring)>1:
        return iter_apply(qc,next_bitstring,i+1,num_qubits)
    else:
        return qc

def apply_convert(qc,bitstring):
    num_qubits = len(bitstring)
    qc.x(num_qubits - 1)
    qc.h(num_qubits - 1)
    iter_apply(qc,bitstring,1,num_qubits)

def reversed_iter_apply(qc,bitstring,i,num_qubits):
    flip = bitstring[0]==0
    if flip:
        bitstring = [not(j) for j in bitstring]
    if len(bitstring)>1:
        reversed_iter_apply(qc,bitstring[1:],i+1,num_qubits)
    else:
        return qc
    qc.cx(num_qubits - i,num_qubits-(i+1))
    if bitstring[1]:
        qc.x(num_qubits-i-1)
    return qc
    

def reverse_apply_convert(qc,bitstring):
    ## 1111
    num_qubits = len(bitstring)
    reversed_iter_apply(qc,bitstring,1,num_qubits)
    qc.h(num_qubits - 1)
    qc.x(num_qubits - 1)
    ## 1111+0111
    ##find bit start with 1


def get_circuit(num_qubits,t,bitstring):
    qc = QuantumCircuit(num_qubits)
    # for i in range(num_qubits):
    #     if i == index:
    #         qc.x(i)
    reverse_apply_convert(qc,bitstring)
    qc.barrier(label='convert')
    qc.mcp(-2*np.pi * t, list(range(1,num_qubits)),0)
    qc.barrier(label='multi-ctrl')
    qc.x(num_qubits-1)
    
    qc.mcp(2*np.pi * t, list(range(1,num_qubits)),0)
    qc.x(num_qubits-1)
    qc.barrier(label='reverse')
    # qc.mcp(-2*np.pi * t, list(range(num_qubits-1)),num_qubits-1)
    apply_convert(qc,bitstring)

    # for i in range(num_qubits):
    #     if i == index:
    #         qc.x(i)
    return qc
t = 0.9
bitstring = [0,0,1,1]
num_q = len(bitstring)
qc =get_circuit(num_q,t,bitstring)

import numpy as np
unitary = get_circ_unitary(qc)
unitarymatrix= np.where(np.abs(unitary.data) < 1e-10, 0, unitary.data)
print(unitarymatrix.round(4))
print(qc.draw(fold=200))

[[1.   -0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j   ]
 [0.   +0.j    1.   -0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j   ]
 [0.   +0.j    0.   +0.j    1.   -0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j   ]
 [0.   +0.j    0.   +0.j    0.   +0.j    0.809+0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.588j 0.   +0.j    0.   +0.j    0.   +0.j   ]
 [0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    1.   -0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j  

In [199]:
np.allclose(unitarymatrix- get_simulate_unitary(t,bitstring), 0, atol=1e-10)

True

In [200]:
t =0.9
v = [0, 1, 0]

# for unitary build contrary_v
contrary_v = [not(i) for i in v]
U = expm(-1j * 2 * np.pi * t * (tensor_product(v)+tensor_product(contrary_v)))
U

array([[1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.809+0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.588j, 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.588j, 0.   +0.j   , 0.   +0.j   , 0.809+0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   ]])

In [201]:
def when_1_add_phase(theta):
    circ = QuantumCircuit(1)
    circ.unitary(np.array([[1, 0], [0, np.exp(1j * theta)]]), 0)
    gate = circ.to_gate()
    return gate
num_qubits = 3
t = 0.9
qc_ham_simu = QuantumCircuit(num_qubits)
gete1 = when_1_add_phase(2 * np.pi * t)
cc_gate1 = MCMT(gete1, num_qubits - 1, 1)
# 哪个是受控门无所谓, 全 1 加相位
qc_ham_simu.append(cc_gate1, range(num_qubits))
get_circ_unitary(qc_ham_simu)

Operator([[1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.809-0.588j]],
       

In [202]:
qc_ham= QuantumCircuit(num_qubits)
qc_ham.mcp(2*np.pi * t, list(range(1,num_qubits)),0)
get_circ_unitary(qc_ham)

Operator([[1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   ],
          [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.809-0.588j]],
       

In [203]:
np.allclose(get_circ_unitary(qc_ham_simu)- get_circ_unitary(qc_ham),0)

True

In [204]:
num_qubits = 3
qc_ham_simu = QuantumCircuit(num_qubits)

# ==== 酉矩阵开始
qc_ham_simu.cx(num_qubits - 2, num_qubits - 3)
qc_ham_simu.cx(num_qubits - 1, num_qubits - 2)
qc_ham_simu.h(num_qubits - 1)
qc_ham_simu.x(num_qubits - 1)

# 控制门开始

qc_ham_simu.barrier()
qc_ham_simu.mcp(-2*np.pi * t, list(range(1,num_qubits)),0)
qc_ham_simu.barrier()

qc_ham_simu.x(num_qubits - 1)
qc_ham_simu.mcp(2*np.pi * t, list(range(1,num_qubits)),0)
qc_ham_simu.x(num_qubits - 1)
qc_ham_simu.barrier()
# 控制门结束

qc_ham_simu.x(num_qubits - 1) 
qc_ham_simu.h(num_qubits - 1)
qc_ham_simu.cx(num_qubits - 1, num_qubits - 2)
qc_ham_simu.cx(num_qubits - 2, num_qubits - 3)
# ==== 酉矩阵结束
print(qc_ham_simu.draw(fold=200))
print(f'酉矩阵作用后:\n {np.asarray(get_circ_unitary(qc_ham_simu))}')

     ┌───┐                ░             ░                      ░                ┌───┐
q_0: ┤ X ├────────────────░──■──────────░───────■──────────────░────────────────┤ X ├
     └─┬─┘┌───┐           ░  │          ░       │              ░           ┌───┐└─┬─┘
q_1: ──■──┤ X ├───────────░──■──────────░───────■──────────────░───────────┤ X ├──■──
          └─┬─┘┌───┐┌───┐ ░  │P(-9π/5)  ░ ┌───┐ │P(9π/5) ┌───┐ ░ ┌───┐┌───┐└─┬─┘     
q_2: ───────■──┤ H ├┤ X ├─░──■──────────░─┤ X ├─■────────┤ X ├─░─┤ X ├┤ H ├──■───────
               └───┘└───┘ ░             ░ └───┘          └───┘ ░ └───┘└───┘          
酉矩阵作用后:
 [[1.   -0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j   ]
 [0.   +0.j    1.   -0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j   ]
 [0.   +0.j    0.   +0.j    0.809+0.j    0.   +0.j    0.   +0.j    0.   +0.588j 0.   +0.j    0.   +0.j   ]
 [0.   +0.j    0.   +0.j    0.   +0.j    1.   -0.j    0.   +0.j    0

In [205]:
print(qc.draw(fold=200))

     ┌───┐┌───┐                convert             multi-ctrl                      reverse ┌───┐               ┌───┐
q_0: ┤ X ├┤ X ├───────────────────░─────■──────────────░────────────■─────────────────░────┤ X ├───────────────┤ X ├
     └─┬─┘├───┤                   ░     │              ░            │                 ░    └───┘          ┌───┐└─┬─┘
q_1: ──■──┤ X ├───────────────────░─────■──────────────░────────────■─────────────────░───────────────────┤ X ├──■──
          └─┬─┘┌───┐┌───┐         ░     │              ░            │                 ░    ┌───┐     ┌───┐└─┬─┘     
q_2: ───────■──┤ X ├┤ X ├─────────░─────■──────────────░────────────■─────────────────░────┤ X ├─────┤ X ├──■───────
               └─┬─┘├───┤┌───┐    ░     │P(-9π/5)      ░      ┌───┐ │P(9π/5) ┌───┐    ░    ├───┤┌───┐└─┬─┘          
q_3: ────────────■──┤ H ├┤ X ├────░─────■──────────────░──────┤ X ├─■────────┤ X ├────░────┤ X ├┤ H ├──■────────────
                    └───┘└───┘    ░                    ░      └─

In [206]:
num_qubits = 3
qc_ham_simu = QuantumCircuit(num_qubits)

# ==== 酉矩阵开始
qc_ham_simu.cx(num_qubits - 2, num_qubits - 3)
qc_ham_simu.cx(num_qubits - 1, num_qubits - 2)
qc_ham_simu.h(num_qubits - 1)
qc_ham_simu.x(num_qubits - 1)

# 控制门开始

qc_ham_simu.barrier()
# gate1: 对角阵 |0>态不动 |1>态加相位-e^it
gete1 = when_1_add_phase(-2 * np.pi * t)
cc_gate1 = MCMT(gete1, num_qubits - 1, 1)
# 哪个是受控门无所谓, 全 1 加相位
qc_ham_simu.append(cc_gate1, range(num_qubits))
qc_ham_simu.barrier()

# gate2: 对角阵 |0>态不动 |1>态加相位e^it
gete2 = when_1_add_phase(2 * np.pi * t)
cc_gate2 = MCMT(gete2, num_qubits - 1, 1)
qc_ham_simu.x(num_qubits - 1)
qc_ham_simu.append(cc_gate2, range(num_qubits))
qc_ham_simu.x(num_qubits - 1)
qc_ham_simu.barrier()
# 控制门结束

qc_ham_simu.x(num_qubits - 1) 
qc_ham_simu.h(num_qubits - 1)
qc_ham_simu.cx(num_qubits - 1, num_qubits - 2)
qc_ham_simu.cx(num_qubits - 2, num_qubits - 3)
# ==== 酉矩阵结束
print(qc_ham_simu.draw(fold=200))
print(f'酉矩阵作用后:\n {np.asarray(get_circ_unitary(qc_ham_simu))}')

     ┌───┐                ░ ┌───────┐ ░      ┌───────┐      ░                ┌───┐
q_0: ┤ X ├────────────────░─┤0      ├─░──────┤0      ├──────░────────────────┤ X ├
     └─┬─┘┌───┐           ░ │       │ ░      │       │      ░           ┌───┐└─┬─┘
q_1: ──■──┤ X ├───────────░─┤1 mcmt ├─░──────┤1 mcmt ├──────░───────────┤ X ├──■──
          └─┬─┘┌───┐┌───┐ ░ │       │ ░ ┌───┐│       │┌───┐ ░ ┌───┐┌───┐└─┬─┘     
q_2: ───────■──┤ H ├┤ X ├─░─┤2      ├─░─┤ X ├┤2      ├┤ X ├─░─┤ X ├┤ H ├──■───────
               └───┘└───┘ ░ └───────┘ ░ └───┘└───────┘└───┘ ░ └───┘└───┘          
酉矩阵作用后:
 [[1.   -0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j   ]
 [0.   +0.j    1.   -0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j   ]
 [0.   +0.j    0.   +0.j    0.809+0.j    0.   +0.j    0.   +0.j    0.   +0.588j 0.   +0.j    0.   +0.j   ]
 [0.   +0.j    0.   +0.j    0.   +0.j    1.   -0.j    0.   +0.j    0.   +0.j    0.   +0.j

In [207]:
get_simulate_unitary(t,v)

array([[1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.809+0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.588j, 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.588j, 0.   +0.j   , 0.   +0.j   , 0.809+0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 1.   +0.j   ]])