In [1]:
import numpy as np
import sys
sys.path.append('../../')
import z_library.linear_system as ls
ls.set_print_form()
cstt = ls.gnrt_cstt(2, 2)
ls.find_basic_solution(cstt)

array([[-1,  1, -1,  1, -1,  1,  0,  0,  0,  0],
       [ 0,  0,  1, -1,  0,  0, -1,  1,  0,  0],
       [ 1, -0,  0,  0,  0,  0,  1,  0,  1,  0],
       [ 0,  1, -1,  1,  0,  0,  1,  0,  0,  1]])

In [2]:
def gnrt_basic_solution(n, m):
  # 自由变量个数
  row = n * m - m + n
  column = 2 * m * n + n
  matrix = np.zeros((row, column))
  # p1
  for i in range(n - 1):
    matrix[i, 0] = -1
    matrix[i, i + 1] = 1
    for j in range(m):
      matrix[i, n + j * n] = -1
      matrix[i, n + j * n + i + 1] = 1
  # p2
  for j in range(m - 1):
    for i in range(n - 1):
      matrix[n - 1 + j * (n - 1) + i, n + j * n] = 1
      matrix[n - 1 + j * (n - 1) + i, n + j * n + i + 1] = -1
      matrix[n - 1 + j * (n - 1) + i, n + m * n + j * n] = -1
      matrix[n - 1 + j * (n - 1) + i, n + m * n + j * n + i + 1] = 1
  # p3
  matrix[n - 1 + (m - 1) * (n - 1), 0]= 1
  for j in range(m):
    matrix[n - 1 + (m - 1) * (n - 1), n + n * m  + n * j]= 1
  # p4
  for i in range(n - 1):
    matrix[n - 1 + (m - 1) * (n - 1) + i + 1, i + 1] = 1
    matrix[n - 1 + (m - 1) * (n - 1) + i + 1, n + n * m + n * (m - 1) + i + 1] = 1
    for j in range(m - 1):
      matrix[n - 1 + (m - 1) * (n - 1) + i + 1, n + j * n] = -1
      matrix[n - 1 + (m - 1) * (n - 1) + i + 1, n + j * n + i + 1] = 1
      matrix[n - 1 + (m - 1) * (n - 1) + i + 1, n  + n * m + j * n] = 1
  return matrix

m = 5
n = 3
print(ls.find_basic_solution(ls.gnrt_cstt(m ,n)) - gnrt_basic_solution(m, n))

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0

In [3]:
m = 20
n = 30

In [4]:
%timeit a = ls.find_basic_solution(ls.gnrt_cstt(m ,n))

12.2 s ± 925 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit b = gnrt_basic_solution(m, n)

702 µs ± 3.01 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
gnrt_basic_solution(5, 4)

array([[-1,  1,  0,  0,  0, -1,  1,  0,  0,  0, -1,  1,  0,  0,  0, -1,  1,  0,  0,  0, -1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  0,  1,  0,  0, -1,  0,  1,  0,  0, -1,  0,  1,  0,  0, -1,  0,  1,  0,  0, -1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  0,  0,  1,  0, -1,  0,  0,  1,  0, -1,  0,  0,  1,  0, -1,  0,  0,  1,  0, -1,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  0,  0,  0,  1, -1,  0,  0,  0,  1, -1,  0,  0,  0,  1, -1,  0,  0,  0,  1, -1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0, -1,  0,  0,  0,  0,