In [1]:
from quBLP.problemtemplate import GraphColoringProblem as GCP
# gcp = GCP(2,[[0, 1]], False)
# gcp = GCP( 2,[], False)
gcp = GCP(3,[[0, 1]], False)
gcp.set_optimization_direction('min')
# gcp = GCP(4,[[0, 1], [1, 2], [2, 3], [3, 0]], False)
# 这个层数和迭代次数要稍微多一点.
# gcp.set_algorithm_optimization_method('HEA', 40)
gcp.optimize(params_optimization_method='COBYLA', max_iter=300, num_layers=5, need_draw=False)
# print(gcp.solution)

0
3
6
1
4
7
2
5
8
linear_objective_vector:
 []


Exception ignored in: <bound method IPythonKernel._clean_thread_parent_frames of <ipykernel.ipkernel.IPythonKernel object at 0x7f2fcff83c10>>
Traceback (most recent call last):
  File "/home/jiangqifan/Tools/anaconda3/envs/FLP/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 770, in _clean_thread_parent_frames
    def _clean_thread_parent_frames(
KeyboardInterrupt: 


In [2]:
from quBLP.utils.quantum_lib import *
import numpy as np
np.set_printoptions(threshold=np.inf, suppress=True, precision=4,  linewidth=300)
num_graphs = 2
num_colors = num_graphs
num_adjacent = 1
num_variables = num_graphs * num_colors + num_colors * num_adjacent
def add_in_target(num_qubits, target_qubit, gate=np.array([[1, 0],[0, -1]])):
    H = np.eye(2 ** (target_qubit))
    H = np.kron(H, gate)
    H = np.kron(H, np.eye(2 ** (num_qubits - 1 - target_qubit)))
    return H
# odd_even = -1 if num_graphs % 2 else 1
# num_qubits = num_variables
# Hp = np.zeros((2**num_qubits, 2**num_qubits))
# for j in range(num_colors):
#     Ht = np.eye(2**num_qubits)
#     for i in range(num_graphs):
#         Ht = Ht @ add_in_target(num_qubits, i + j * num_graphs, (gate_z + gate_I)/2)
#     Hp += np.eye(2**num_qubits) - odd_even * Ht
# print(Hp)

odd_even = -1 if num_graphs % 2 else 1
num_qubits = num_variables
Hp = np.zeros((2**num_qubits, 2**num_qubits))
for j in range(num_colors):
    Ht = np.eye(2**(num_qubits - num_graphs * num_colors))
    for i in range(num_graphs * num_colors):
        Ht = np.kron((gate_z + gate_I)/2, Ht)
    Hp += np.eye(2**num_qubits) - odd_even * Ht
print(Hp)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0.

In [19]:
2*np.array([[1,3],[2]])

/tmp/ipykernel_1620497/2085036213.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  2*np.array([[1,3],[2]])


array([list([1, 3, 1, 3]), list([2, 2])], dtype=object)

In [11]:
[1] * 3

[1, 1, 1]

In [12]:
3 * np.array([1])

array([3])

In [20]:
3 * np.array([1]) * 3

array([9])

In [36]:
np.concatenate((2 * np.array([1] * 3), np.array([0] * 5)))

array([2, 2, 2, 0, 0, 0, 0, 0])

In [37]:
a=3
-a


-3